version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"


volumes:
  postgres:
