package pl.futurecollars.invoicing.dto;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.UUID;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class InvoiceListDto {

    @ApiModelProperty(value = "UUID generated by app", example = "123e4567-e89b-12d3-a456-426614174000")
    private UUID invoiceId;

    @ApiModelProperty(value = "Invoice number", required = true, example = "2021/09/30/000123")
    private String invoiceNumber;

    @ApiModelProperty(value = "Invoice issue date", required = true, example = "2021-09-30")
    private LocalDate issueDate;

    @ApiModelProperty(value = "Issuer name", required = true)
    private String issuerName;

    @ApiModelProperty(value = "Receiver name", required = true)
    private String receiverName;

}
